// Code generated by mockery v2.10.0. DO NOT EDIT.

package mocks

import (
	gin "github.com/gin-gonic/gin"
	mock "github.com/stretchr/testify/mock"
)

// AccountController is an autogenerated mock type for the AccountController type
type AccountController struct {
	mock.Mock
}

// CreateAccountHandler provides a mock function with given fields:
func (_m *AccountController) CreateAccountHandler() func(*gin.Context) {
	ret := _m.Called()

	var r0 func(*gin.Context)
	if rf, ok := ret.Get(0).(func() func(*gin.Context)); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(func(*gin.Context))
		}
	}

	return r0
}

// FetchAccountHandler provides a mock function with given fields:
func (_m *AccountController) FetchAccountHandler() func(*gin.Context) {
	ret := _m.Called()

	var r0 func(*gin.Context)
	if rf, ok := ret.Get(0).(func() func(*gin.Context)); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(func(*gin.Context))
		}
	}

	return r0
}
