// Code generated by mockery v2.10.0. DO NOT EDIT.

package mocks

import (
	gin "github.com/gin-gonic/gin"
	mock "github.com/stretchr/testify/mock"
)

// TransactionController is an autogenerated mock type for the TransactionController type
type TransactionController struct {
	mock.Mock
}

// CreateTransationHandler provides a mock function with given fields:
func (_m *TransactionController) CreateTransationHandler() func(*gin.Context) {
	ret := _m.Called()

	var r0 func(*gin.Context)
	if rf, ok := ret.Get(0).(func() func(*gin.Context)); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(func(*gin.Context))
		}
	}

	return r0
}

// ListTransationHandler provides a mock function with given fields:
func (_m *TransactionController) ListTransationHandler() func(*gin.Context) {
	ret := _m.Called()

	var r0 func(*gin.Context)
	if rf, ok := ret.Get(0).(func() func(*gin.Context)); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(func(*gin.Context))
		}
	}

	return r0
}
